# Generated by Django 3.2 on 2022-01-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Locataire',
            new_name='client',
        ),
    ]
